services:
  php:
    build: "../"
    container_name: controle-acesso
    expose:
      - "80"
    volumes:
      - ../:/var/www/html
    networks:
      - postgres_default

  nginx:
    image: nginx:alpine
    container_name: controle-acesso-nginx
    ports:
      - "8080:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/certs
    depends_on:
      - php
    networks:
      - postgres_default

networks:
  postgres_default:
    external: true
