events {}

http {
  server {
    listen 443 ssl;
    server_name 192.168.0.10;

    ssl_certificate_key /certs/192.168.0.10+1-key.pem;
    ssl_certificate /certs/192.168.0.10+1.pem;

    location / {
      proxy_pass http://controle-acesso:80;
    }
  }
}